// web-clients/vue/src/components/MessageList/EmptyListInfo.vue
<template>
  <div class="message empty-container">
    <p>
      <strong>We don&apos;t have any messages yet</strong>
    </p>
    <p>Be the first to spread your words!</p>
  </div>
</template>

<script>
export default {
  name: 'EmptyListInfo',
};
</script>

<style scoped>
.empty-container {
  color: var(--secondary-color);
  padding: 2vh;
  text-align: center;
}

.message {
  background: var(--content-bg-color);
  border: 1px solid var(--border-color);
  margin-bottom: 1vh;
  padding: 2vh 1vw;
}

.message p {
  font-size: 1rem;
  margin: 0 0 1.5vh;
}
</style>

// web-clients/react/src/Components/MessageList/EmptyListInfo.js
import React from "react";
import { emptyContainer, message as messageClass } from "./_style.css";

const EmptyListInfo = () => (
  <div className={`${messageClass} ${emptyContainer}`}>
    <p>
      <strong>We don&apos;t have any messages yet</strong>
    </p>
    <p>Be the first to spread your words!</p>
  </div>
);

export default EmptyListInfo;
