// web-clients/react/src/Components/Ranking/EmptyRankingInfo.js
import React from "react";
import { emptyContainer as emptyContainerClass } from "./_style.css";

const EmptyRankingInfo = () => (
  <div className={emptyContainerClass}>
    <p>Our ranking is still empty</p>
    <p>Vote for some messages and refresh the page to see the results</p>
  </div>
);

export default EmptyRankingInfo;

// web-clients/vue/src/components/Ranking/EmptyRankingInfo.vue
<template>
  <div class="empty-container">
    <p>Our ranking is still empty</p>
    <p>Vote for some messages and refresh the page to see the results</p>
  </div>
</template>

<script>
export default {
  name: 'EmptyRankingInfo',
};
</script>

<style scoped>
.empty-container {
  color: var(--secondary-color);
}
</style>
