// web-clients/react/src/Components/MessageList/index.js
import React from "react";
import InfiniteScroll from "react-infinite-scroller";
import EmptyListInfo from "./EmptyListInfo";
import Message from "./Message";
import {
  MESSAGE_CREATED,
  eventBus,
  get as getMessages,
} from "../../apis/messageApi";

class MessageList extends React.Component {
  static async getInitialProps() {
    const messages = await getMessages();
    return {
      messages,
    };
  }

  constructor(props) {
    super(props);

    this.loadNextPage = this.loadNextPage.bind(this);
    this.reload = this.reload.bind(this);

    this.state = {
      hasMore: true,
      messages: props.messages,
    };
  }

  componentDidMount() {
    eventBus.addListener(MESSAGE_CREATED, this.reload);
  }

  componentWillUnmount() {
    eventBus.removeListener(MESSAGE_CREATED, this.reload);
  }

  async loadNextPage() {
    const lastMessageId = this.state.messages.length
      ? this.state.messages[this.state.messages.length - 1].id
      : undefined;

    const messages = await getMessages(lastMessageId);
    this.setState(prevState => ({
      hasMore: messages.length > 0,
      messages: prevState.messages.concat(messages),
    }));
  }

  async reload() {
    const messages = await getMessages();
    this.setState({
      hasMore: true,
      messages,
    });
  }

  render() {
    if (this.state.messages.length) {
      return (
        <InfiniteScroll
          hasMore={this.state.hasMore}
          loadMore={this.loadNextPage}
        >
          {this.state.messages.map(m => (
            <Message key={m.id} id={m.id} created={m.created} text={m.text} />
          ))}
        </InfiniteScroll>
      );
    }

    return <EmptyListInfo />;
  }
}

export default MessageList;

// web-clients/vue/src/components/MessageList/index.vue
<template>
  <div v-if="messages.length">
    <Message 
      v-for="item in messages"
      v-bind="item" 
      :key="item.id" />
      
    <InfiniteLoading @infinite="infiniteHandler">
      <span slot="no-more">
        There is no more messages :(
      </span>
    </InfiniteLoading>
  </div>
  <EmptyListInfo v-else />
</template>

<script>
import InfiniteLoading from 'vue-infinite-loading';
import EmptyListInfo from './EmptyListInfo';
import Message from './Message'
import { EventBus, get as getMessages, MESSAGE_CREATED } from "../../apis/messageApi";

export default {
  name: 'MessageList',
  components: {
    EmptyListInfo,
    InfiniteLoading,
    Message
  },
  data() {
    return {
      messages: []
    }
  },
  beforeDestroy() {
    EventBus.$off(MESSAGE_CREATED, this.loadMessages);
  },
  created () {
    EventBus.$on(MESSAGE_CREATED, this.loadMessages);
    this.loadMessages();
  },
  methods: {
    async infiniteHandler($state) {
      const lastMessageId = this.messages.length
        ? this.messages[this.messages.length - 1].id
        : undefined;

      const result = await getMessages(lastMessageId);
      $state.loaded();
      if (result.length) {
        this.messages = this.messages.concat(result);
      } else {
        $state.complete();
      }
    },
    async loadMessages() {
      this.messages = await getMessages();
    }
  }, 
}
</script>
