// web-clients/react/src/MessageList.js
import React from "react";
import InfiniteScroll from "react-infinite-scroller";
import Message from "./Message";
import { get as getMessages } from "./apis/messageApi";

class MessageList extends React.Component {
  constructor(props) {
    super(props);

    this.loadNextPage = this.loadNextPage.bind(this);

    this.state = {
      messages: [],
    };
  }

  componentDidMount() {
    this.loadNextPage();
  }

  loadNextPage() {
    getMessages(this.state.from).then(result => {
      const lastRecord = result.length
        ? result[result.length - 1].id
        : undefined;

      this.setState(prevState => ({
        messages: prevState.messages.concat(result),
        from: lastRecord,
      }));
    });
  }

  render() {
    if (!this.state.messages) {
      return <div>Empty</div>;
    }

    return (
      <InfiniteScroll
        hasMore={this.state.from !== undefined}
        loadMore={this.loadNextPage}
      >
        {this.state.messages.map((m, index) => (
          <Message key={index} created={m.created} text={m.text} />
        ))}
      </InfiniteScroll>
    );
  }
}

export default MessageList;

// web-clients/vue/src/components/MessageList/index.vue
<template>
  <div v-if="messages.length">
    <Message 
      v-for="item in messages"
      v-bind="item" 
      :key="item.id" />
      
    <InfiniteLoading @infinite="infiniteHandler">
      <span slot="no-more">
        There is no more messages :(
      </span>
    </InfiniteLoading>
  </div>
  <EmptyListInfo v-else />
</template>

<script>
import InfiniteLoading from 'vue-infinite-loading';
import EmptyListInfo from './EmptyListInfo';
import Message from './Message'
import { EventBus, get as getMessages, MESSAGE_CREATED } from "../../apis/messageApi";

export default {
  name: 'MessageList',
  components: {
    EmptyListInfo,
    InfiniteLoading,
    Message
  },
  data() {
    return {
      messages: []
    }
  },
  beforeDestroy() {
    EventBus.$off(MESSAGE_CREATED, this.loadMessages);
  },
  created () {
    EventBus.$on(MESSAGE_CREATED, this.loadMessages);
    this.loadMessages();
  },
  methods: {
    async infiniteHandler($state) {
      const lastMessageId = this.messages.length
        ? this.messages[this.messages.length - 1].id
        : undefined;

      const result = await getMessages(lastMessageId);
      $state.loaded();
      if (result.length) {
        this.messages = this.messages.concat(result);
      } else {
        $state.complete();
      }
    },
    async loadMessages() {
      this.messages = await getMessages();
    }
  }, 
}
</script>
