// web-clients/react/src/Components/MessageList/VoteContainer.js
import React, { useContext, useEffect, useState } from "react";
import PropTypes from "prop-types";
import Octicon, { Thumbsdown, Thumbsup } from "@primer/octicons-react";
import { OfflineContext } from "../OfflineContext";
import { btnVote as btnVoteClass } from "./_style.css";
import { get as getVotes, post } from "../../apis/voteApi";

function VoteContainer({ subjectId }) {
  const offlineContext = useContext(OfflineContext);
  const [votes, setVotes] = useState({
    voted: false,
  });

  useEffect(() => {
    async function load() {
      const response = await getVotes(subjectId);
      setVotes(response);
    }

    load();
  }, [subjectId]);

  async function submitVote(optionName) {
    const response = await post(subjectId, optionName);
    setVotes({ ...votes, ...response, voted: true });
  }

  const voteEnabled = !votes.voted && offlineContext.online;
  return (
    <div>
      <button
        aria-label="Like this message"
        className={btnVoteClass}
        disabled={!voteEnabled}
        onClick={() => submitVote("like")}
      >
        <Octicon icon={Thumbsup} /> {votes.like || 0}
      </button>
      <button
        aria-label="Dislike this message"
        className={btnVoteClass}
        disabled={!voteEnabled}
        onClick={() => submitVote("dislike")}
      >
        <Octicon icon={Thumbsdown} /> {votes.dislike || 0}
      </button>
    </div>
  );
}

VoteContainer.propTypes = {
  subjectId: PropTypes.number.isRequired,
};

export default React.memo(VoteContainer);

// web-clients/vue/src/components/MessageList/VoteContainer.vue
<template>
  <div>
    <button 
      :disabled="voted" 
      aria-label="Like this message"
      class="btn-vote"
      @click="submiteVote('Like')">
      <Octicon ico="thumbsup" /> {{ like }}
    </button>
    <button 
      :disabled="voted" 
      aria-label="Dislike this message" 
      class="btn-vote" 
      @click="submiteVote('Dislike')">
      <Octicon ico="thumbsdown" /> {{ dislike }}
    </button>
  </div>
</template>

<script>
import Octicon from "../Octicon";
import { get as getVotes, post } from "../../apis/voteApi"

export default {
  name: 'VoteContainer',
  components: {
    Octicon
  },
  props: {
    subjectId: {
      type: Number,
      required: true
    }
  },
  data() {
    return {
      dislike: 0,
      like: 0,
      voted: false
    };
  },
  async created() {
    const response = await getVotes(this.subjectId);
    this.updateVoteCount(response);
  },
  methods: {
    async submiteVote(optionName) {
      const response = await post(this.subjectId, optionName);
      this.updateVoteCount(response);
      this.voted = true;
    },
    updateVoteCount(data) {
      if (data.like)
        this.like = data.like;

      if (data.dislike)
        this.dislike = data.dislike;
    }
  }
}
</script>

<style scoped>
.btn-vote {
  background: transparent;
  border: 0;
  color: var(--secondary-color);
  cursor: pointer;
  margin-right: 1vw;
  padding: 0;
}

.btn-vote:disabled {
  color: var(--disabled-color);
  cursor: not-allowed;
}

.btn-vote span {
  margin-right: 0.5vw;
  font-size: 0.8rem;
}
</style>
